import { execFile } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

// 8-bit chiptune effects generated by scripts/make-sounds.js (see `npm run sounds`)
const SOUND_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "assets", "sounds");
const LADDER_STEPS = 6; // correct-0 … correct-5: the pitch climbs with your combo

export function createAlerts(initial = {}) {
  const enabled = process.platform === "darwin";
  const config = { sound: true, volume: 0.5, ...initial };

  const play = (name) => {
    if (!config.sound || !enabled) return;
    execFile("afplay", ["-v", String(config.volume), path.join(SOUND_DIR, `${name}.wav`)], () => {});
  };

  return {
    play,
    configure: (patch) => Object.assign(config, patch),
    // a new question while you're in another window: sound plus a Notification Center banner
    ask() {
      play("ask");
      if (enabled) execFile("osascript", ["-e", 'display notification "A new word is waiting" with title "Dracosh"'], () => {});
    },
    // The biggest thing that just happened wins: evolution > goal > combo cheer > the answer itself.
    // On a plain correct answer the pitch rises with the combo and resets on a miss. Badges ring
    // on their own, each as its line lights up (see BadgeUnlock).
    result(result, { cheers = [], combo = 0 } = {}) {
      if (result === "wrong") return play("wrong");
      for (const kind of ["evolve", "goal", "combo"]) {
        if (cheers.includes(kind)) return play(kind);
      }
      if (result === "typo") return play("close");
      play(`correct-${Math.min(Math.max(combo - 1, 0), LADDER_STEPS - 1)}`);
    }
  };
}
